apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-prod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-prod
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
       # - name:  MYSQL_ROOT_PASSWORD
        #  valueFrom: 
         #   secretKeyRef:
          #    name: mysql-secret
           #   key: mysql-password
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
              claimName: mysql-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-prod
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None