apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prod
  template:
    metadata:
      labels:
        app: nginx-prod
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        env:
        #- name: USER_NAME
         # valueFrom: 
          #  secretKeyRef:
           #   name: mysql-secret
            #  key: mysql-user
        - name: USER_PWD
          valueFrom: 
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-url
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30300